name: Workflow
on:
    push:
        branches:
            - feat-LR-pet-clinic

jobs:
    Build:
        runs-on: ubuntu-latest
        steps: 

        - name: Set Up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log
          run: ls -R
