name: Workflow
on:
    push:
        branches:
            - feat-LR-pet-clinic

jobs:
    SAST:
        runs-on: ubuntu-latest
        steps: 

        - name: Set Up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Checkout code
          uses: actions/checkout@v2

        # Proyecto Java
        # - name: Build
        #   run: |
        #     chmod 777 gradlew
        #     ./gradlew build

        - name: Validando tipo de proyecto
          id: tipoProyecto
          run: |
            if [ -f "build.gradle"]
            then
                echo "Proyecto JAVA"
                if grep -q 'id "org.sonarqube" version "3.3"'' build.gradle
                then
                    echo "El plugin de SonaCloud ya esta presente en el build.gradle"
                else
                    sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
                    echo "El plugin de SonaCloud no esta presente y se ha añadido en el build.gradle"
                    cat build.gradle
                fi
            else
                echo "tipo de proyecto desconocido"
            fi

